### ISSUE TITLE
Failed NPM Audit

### ISSUE THREAD

**Issue by robert-gruner** [pingyhq/nm-prune#12]
Hi guys,

recent "npm audit" reports find high security vulnerabilities. On Nodejs v14.18.0 with NPM v6.14.15 we receive the following audit logs:

> High          │ Prototype Pollution in set-value                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ set-value                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nm-prune [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nm-prune > prompt-confirm > prompt-base > prompt-question >  │
│               │ prompt-choices > set-value                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-4jqc-8m5r-9rpr            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service in trim-newlines        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ trim-newlines                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nm-prune [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nm-prune > meow > trim-newlines                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-7p7h-4mm5-852v            │
└───────────────┴──────────────────────────────────────────────────────────────┘

Is there any chance to get a fresh release for this lib where the dependencies are updated?

Regards,
Robert

**Comment by davej** [comment]
Hey @robert-gruner, happy to accept a PR and do a release. :)

**Comment by robert-gruner** [comment]
Hi @davej 

opened a PR for it: https://github.com/pingyhq/nm-prune/pull/13 Dependencies were a bit outdated. ;)

Most important are the changes regarding meow and enquirer. These are the "production" deps. The upgrades of ava and package-preview were easy, so I integrated them.

Because of the replacement of "prompt-confirm" the CLI prompt looks slightly different. Functionality is similar so I thought it is ok.

eslint upgrades might be a bit more config and are connected to your code style. So I did not fiddle with it.

Please do a proper test & code review of the changes before release. I hope I have not missed anything.

Regards,
Robert
