### ISSUE TITLE
How does this differ from yarn autoclean?

### ISSUE THREAD

**Issue by hulkish** [pingyhq/nm-prune#5]

**Comment by davej** [comment]
It's pretty similar except that it's not tied to any particular package manager. nm-prune can be used with npm or yarn. It's also very lightweight which makes it ideal to add to your project's `devDependencies` and `scripts`.

**Comment by hulkish** [comment]
@davej that's pretty cool...I stumbled on this while experimenting with the following idea:

1. provide an entry point js file
2. recursively iterate through this entry file and all imported modules,  incrementally aggregate a list of "whitelisted" files.
3. remove all files which are not in this whitelist

happy hacking!

**Comment by davej** [comment]
Sounds good except that dynamic imports would make it very difficult to do reliably.

**Comment by hulkish** [comment]
well you can still detect dynamic imports (im thinking with babel).. but you're right that the idea has a challenge of falling short for edge cases

**Comment by davej** [comment]
Yeah, you can detect them and try to parse them but often they are not deterministic. I'm thinking of stuff like this:
```js
require(`./${os.platform()}-${appFirstRun ? 'init' : 'resume'}`);
```
