### ISSUE TITLE
please remove useless log

### ISSUE THREAD

**Issue by isayme** [pingyhq/nm-prune#6]
`log(info.files.map(fullPath => fs.remove(fullPath)));`
 
![image](https://user-images.githubusercontent.com/1747852/33532689-bf1043d6-d8d6-11e7-8c13-bb2cfceca9d1.png)

**Comment by davej** [comment]
Oops. Thanks, I'll remove it in an hour or two when I'm in front of a computer. 👍

**Comment by davej** [comment]
Published in `v2.0.2`

**Comment by isayme** [comment]
why not `v2.0.1`?

**Comment by davej** [comment]
Haha. I accidentally ran `npm version patch` twice and didn't bother fixing it.

**Comment by isayme** [comment]
ok~~~
