### ISSUE TITLE
lowercase file names are not deleted

### ISSUE THREAD

**Issue by Marko-Jankovic** [pingyhq/nm-prune#7]
eg. in default-prune.json you have specified "LICENSE" but "license" file is not deleted.

**Comment by Marko-Jankovic** [comment]
btw maybe you should add "extends" field so we can extend your json configuration localy

**Comment by Marko-Jankovic** [comment]
aha, prune.json is for extending... sorry

**Comment by davej** [comment]
Thanks. Fixed and released in `v3.0.0`. Prunefile entries should always be specified in lowercase from v3 onward.

**Comment by davej** [comment]
I'm not going to add extends support yet but will take a PR for it.

Of course you can just [copy and paste the `default-prune.json` into your own prune file](https://github.com/pingyhq/nm-prune#customizing-files-and-folders-to-be-pruned).

**Comment by Marko-Jankovic** [comment]
Cool. Thank you for quick fix!
