### ISSUE TITLE
A flag to keep LICENSE files

### ISSUE THREAD

**Issue by zkochan** [pingyhq/nm-prune#9]
I use [publish-packed](https://github.com/zkochan/publish-packed) for bundling and releasing pnpm. The bundled node_modules weights around 7 MB. I'd like to use nm-prune on the bundled node_modules to reduce its size. However, I need to keep the LICENSE files because they state that:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So it would be great to have an option like `--keep-license` in nm-prune

**Comment by davej** [comment]
Makes sense, I think I'll do a breaking change and default to keeping license files. I'll add a flag that allows users to discard licenses if they want.  I'll make the changes now.

BTW, you can also provide your own `prune.json` if you want to customise it a bit. https://github.com/pingyhq/nm-prune#customizing-files-and-folders-to-be-pruned

**Comment by davej** [comment]
Published as `v4.0.0`.

By default v4+ will not discard license files. If you wish to prune them anyway then you can run the command `nm-prune --prune-license` or `nm-prune -l`.

**Comment by zkochan** [comment]
Awesome! Thanks a lot!
